import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../../components/Layouts/Footer'
import Navbar from '../../components/Layouts/Navbar'

type LayoutProps = {
  title?: string
}

const Layout: NextPage<LayoutProps> = ({ title, children }) => {
  const titleName = title ?? 'Luciabet'
  return (
    <>
      <Head>
        <title>{titleName}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div>{children}</div>
      <Footer />
    </>
  )
}

export default Layout
